### ISSUE TITLE
[ Bug ] BetterNCM崩溃 原因：remove_all:另一个程序正在使用此文件，进程无法访问。："C:\betterncm/plugins_runtime/tmp"

### ISSUE THREAD

**Issue by virdmark** [std-microblock/BetterNCM#445]
### Bug 描述

BetterNCM崩溃
 原因：remove_all:另一个程序正在使用此文件，进程无法访问。："C:\betterncm/plugins_runtime/tmp"

### 复现步骤

打开网易云即弹出,但是弹出之后betterncm还在正常运行。

### 期望行为

-

### 屏幕截图

![image](https://github.com/MicroCBer/BetterNCM/assets/94534273/e297ea87-9918-4537-aa59-6a969262c31a)

### BetterNCM 版本

1.3.0

### 网易云音乐版本

2.10.12(bulid:201849)(patch:1:62cafa7)

### 网易云音乐 Patch 版本

patch:1:62cafa7

### 补充

安装的插件：
![image](https://github.com/MicroCBer/BetterNCM/assets/94534273/5f0ed6b8-913d-4b0b-b251-032d2ffc8d02)

**Comment by MicroCBer** [comment]
暂时没什么头绪 可以稳定复现吗

**Comment by virdmark** [comment]
每次打开网易云都可以稳定复现，我电脑有Hyper-V和linux虚拟机 Ubuntu18.04不知道Hyper-V会不会影响这个东西

**Comment by txyyh** [comment]
看看谁占用了那个文件？PowerToys: File LockSmith 可以看

**Comment by std-microblock** [comment]
fixed
