### ISSUE TITLE
安装BetterNCM后网易云音乐打不开

### ISSUE THREAD

**Issue by CresBigB** [std-microblock/BetterNCM#486]
### Bug 描述

不清楚什么原因，之前一直用的好好的，今天晚上突然间发现网易云音乐打不开，重启电脑已经试过了，关闭杀毒软件也试过了，只有删除BetterNCM才能打开网易云音乐，重装多次问题依旧存在

### 复现步骤

1.安装BetterNCM
2.打开网易云音乐
3.网易云音乐无法打开
4.卸载BetterNCM
5.网易云音乐可以打开

### 期望行为

希望作者可以修复bug，恢复正常使用

### 屏幕截图

https://github.com/MicroCBer/BetterNCM/assets/125197600/4e173694-ace3-4631-ba02-3032d01d0160

### BetterNCM 版本

1.3.2

### 网易云音乐版本

3.0.9(x64)

### 网易云音乐 Patch 版本

9316eed

**Comment by CresBigB** [comment]
找到原因了，应该是我电脑运行库的原因，就在刚刚启动老头环发现打不开，我就知道肯定是库出了问题，用微软运行库修复工具修复了一下就好了

**Comment by yueya520** [comment]
> 找到原因了，应该是我电脑运行库的原因，就在刚刚启动老头环发现打不开，我就知道肯定是库生长问题，用微软运行库修复工具修复关系就好了

微软运行库修复工具分享一下，我的也打不开了
