### ISSUE TITLE
[ Bug ] unblock服务 一直启动失败

### ISSUE THREAD

**Issue by X-nancy** [std-microblock/BetterNCM#515]
### Bug 描述

网易云版本2.10.13，插件1.3.3，发现无论如何都启动不了Unblock，一直启动失败
，请问该如何解决

### 复现步骤

1.下载了Unblock...这个插件
2. 选择最新0.27.8-patch.1/0.27.7版本
3. 点击应用重启/每次启动
4. 显示服务启动失败

### 期望行为

该如何解决

### 屏幕截图

![1](https://github.com/user-attachments/assets/81e57c58-0b3c-4edf-8cdb-000aa86ba08e)
![2](https://github.com/user-attachments/assets/e2cd27ee-de04-4f94-906a-bbe26f13731a)
![3](https://github.com/user-attachments/assets/59baecab-bfa2-4ad9-83b7-58b4d92e384d)

### BetterNCM 版本

1.3.3

### 网易云音乐版本

2.10.13

### 网易云音乐 Patch 版本

12f60b8

**Comment by HUAJILU** [comment]
把better ncm安装器的数据目录改成不带空格等特殊字符的纯英文目录就行了，这个问题在老早之前就有人发出来过了，是解锁插件的锅

**Comment by std-microblock** [comment]
插件问题请向插件反馈
