### ISSUE TITLE
[ Bug ] 提示加载失败 Unexpected token < in JSON at position 0

### ISSUE THREAD

**Issue by Hongtauo** [std-microblock/BetterNCM#516]
### Bug 描述

打开网易云的BetterNCM后，提示加载失败，Unexpected token < in JSON at position 0，更改插件源后仍不正常

### 复现步骤

1. 点击 PluginMarket
2. 加载失败，Unexpected token < in JSON at position 0
3. 设置
4. 更换源
5. 加载失败，Failed to fetch
6. 检查更新失败

### 期望行为

解决插件市场的加载问题

### 屏幕截图

![image](https://github.com/user-attachments/assets/cde0e438-db80-4af5-acfb-6ab797fc342f)

### BetterNCM 版本

1.3.3

### 网易云音乐版本

3.0.3

### 网易云音乐 Patch 版本

8229262

**Comment by CodeBoy2006** [comment]
感觉像是gitcode的问题

访问[gitcode.net](https://gitcode.net)会被重定向到[csdn](https://passport.csdn.net/login?code=applets)

**Comment by CodeBoy2006** [comment]
| URL | 状态 |
|:--- |:---:|
| https://gitcode.net/ | ![HTTP/1.1 301 Moved](https://img.shields.io/badge/HTTP%2F1.1-301%20Moved-yellow) |
| https://gitcode.net/explore | ![HTTP/1.1 302](https://img.shields.io/badge/HTTP%2F1.1-302-yellow) |
| https://gitcode.net/users/sign_in | ![HTTP/1.1 302](https://img.shields.io/badge/HTTP%2F1.1-302-yellow) |
| https://passport.csdn.net/account/login?from=https://gitcode.net/sign_in_callback?requestUrl=/explore | ![HTTP/1.1 302](https://img.shields.io/badge/HTTP%2F1.1-302-yellow) |
| https://passport.csdn.net/login?code=applets | ![HTTP/1.1 200](https://img.shields.io/badge/HTTP%2F1.1-200-brightgreen) |

**Comment by std-microblock** [comment]
fixed
