### ISSUE TITLE
NCMInstaller Can NOT get BetterNCM Version

### ISSUE THREAD

**Issue by StarsailsClover** [std-microblock/BetterNCM#519]
### Bug 描述

NCMInstaller Can NOT get BetterNCM Version, This made I cannot Install BetterNCM With NCM

### 复现步骤

In Windows 11 Insider Preview 27718.1000 (rs_prerelease), Use https://microblock.cc/betterncm ghProxy Download, The file which I downloaded Cannot find the right Version

### 期望行为

Find the right Version, And Install

### BetterNCM 版本

I haven't Installed before

### 网易云音乐版本

2.10.13

### 网易云音乐 Patch 版本

1:12f60b8

**Comment by std-microblock** [comment]
fixed

**Comment by StarsailsClover** [comment]
Thanks! but now I can't Install BNCM in The new NCM Version
