### ISSUE TITLE
When I use Wallpaper Engine, Better NCM Will try to kill My Wallpaper Engine

### ISSUE THREAD

**Issue by StarsailsClover** [std-microblock/BetterNCM#520]
### Bug 描述

When I use Wallpaper Engine, Better NCM (I had Upload a Issue to Solve the Install Problem, This is my friend's BetterNCM Problem ) Will try to kill My Wallpaper Engine, This made my Video Wallpaper Flash All the way.

### 复现步骤

Like what I say in "Bug 描述"

### 期望行为

I hope Wallpaper Engine can work in right way

### BetterNCM 版本

I haven't Installed before

### 网易云音乐版本

2.10.13

### 网易云音乐 Patch 版本

1:12f60b8

**Comment by std-microblock** [comment]
No it wouldn't

**Comment by StarsailsClover** [comment]
I check it. I find that is a problem of Steam, Steam's Workshop have some Bugs(Problems) lead this problem.
