### ISSUE TITLE
下载1.3.4版本的ddl文件替换后，打开后没有插件市场，并且一直显示检查更新中

### ISSUE THREAD

**Issue by xinwen0613** [std-microblock/BetterNCM#522]
### Bug 描述

下载1.3.4版本的ddl文件替换后，打开后没有插件市场，并且一直显示检查更新中。

### 复现步骤

1.先使用最新的installer,适配betterNCM一直在获取中
2.下载1.3.4版本的ddl文件替换后，打开后没有插件市场，并且一直显示检查更新中

### 期望行为

能够正常使用betterNCM

### 屏幕截图

<img width="300" alt="instaler" src="https://github.com/user-attachments/assets/69435b1b-5973-49f6-9549-e0e481255087">
<img width="662" alt="检查更新中" src="https://github.com/user-attachments/assets/6edb779a-25ff-401c-be49-dba4ca3a2bcf">
<img width="848" alt="控制台" src="https://github.com/user-attachments/assets/7cb38da9-d1d1-4f75-9087-2aae6aea34b0">

### BetterNCM 版本

1.3.4

### 网易云音乐版本

3.0.4

### 网易云音乐 Patch 版本

d78a735

**Comment by std-microblock** [comment]
duplicated #523

**Comment by xinwen0613** [comment]
删除PluginMarket.plugin文件后提示由检查更新中变成已是最新版本，但是仍未加载出插件市场

**Comment by std-microblock** [comment]
刷新

**Comment by xinwen0613** [comment]
刷新后仍然无法获取插件市场，控制台仍然下载失败
<img width="793" alt="无法获取插件市场" src="https://github.com/user-attachments/assets/5716cb4e-b6b5-440b-9ec4-e654ce64a4a7">
<img width="840" alt="控制台下载失败" src="https://github.com/user-attachments/assets/97337bda-e979-4352-b4a1-30858d97e3d1">
