### ISSUE TITLE
安装完后就立马闪退，一卸载网易云就马上打开了

### ISSUE THREAD

**Issue by young2898** [std-microblock/BetterNCM#524]
### Bug 描述

安装完后就立马闪退，一卸载网易云就马上打开了，反反复复试了很多次

### 复现步骤

**例**:
1. 转到"...
2. 点击'....'
3. 向下滚动到'....'
4. 看到错误

### 期望行为

解决

### 屏幕截图

![屏幕截图 2024-10-06 015504](https://github.com/user-attachments/assets/49fabf9d-5a1d-4c7b-8d73-dcfd2decb5cf)
![屏幕截图 2024-10-06 015447](https://github.com/user-attachments/assets/582c7087-1a24-432f-b846-9b98779c1a47)

### BetterNCM 版本

1.3.4

### 网易云音乐版本

2.10.12

### 网易云音乐 Patch 版本

看不到

**Comment by herolpj** [comment]
我现在和你一样的问题，首先排除我运行库问题了

**Comment by young2898** [comment]
> 我现在和你一样的问题，首先排除我运行库问题了

我也是，运行库修复过还是一样

**Comment by std-microblock** [comment]
看一眼betterncm文件夹下的日志呢

**Comment by TophTab** [comment]
同样的问题

**Comment by young2898** [comment]
> 看一眼betterncm文件夹下的日志呢

什么也没有，文件夹里面

**Comment by BecherYes** [comment]
我是2.10.6实测betterncm1.3.4安装上就闪退，回退到1.3.3就正常了
![Snipaste_2024-10-06_13-49-47](https://github.com/user-attachments/assets/ac2aeba8-8a78-4e92-bb4c-4373fa58d116)
![Snipaste_2024-10-06_13-49-56](https://github.com/user-attachments/assets/fc28e8cf-2bf6-4007-bd65-8bb8a6a19280)

**Comment by buerka** [comment]
遇到了同样的问题

**Comment by std-microblock** [comment]
[BetterNCMII86.zip](https://github.com/user-attachments/files/17268653/BetterNCMII86.zip)
尝试这个版本

**Comment by herolpj** [comment]
不行

> [BetterNCMII86.zip](https://github.com/user-attachments/files/17268653/BetterNCMII86.zip) 尝试这个版本

**Comment by herolpj** [comment]
还是闪退

**Comment by young2898** [comment]
> 我是2.10.6实测betterncm1.3.4安装上就闪退，回退到1.3.3就正常了
> 
> ![Snipaste_2024-10-06_13-49-47](https://github.com/user-attachments/assets/ac2aeba8-8a78-4e92-bb4c-4373fa58d116)
> 
> ![Snipaste_2024-10-06_13-49-56](https://github.com/user-attachments/assets/fc28e8cf-2bf6-4007-bd65-8bb8a6a19280)
> 
> 

可以，已经解决

**Comment by herolpj** [comment]
网易云最新版本3.0.18的可以打开，但是降级过后的2.10.13版本就打不开了
