### ISSUE TITLE
在插件降级到2.10.几版本后没有batterncm插件显示

### ISSUE THREAD

**Issue by herolpj** [std-microblock/BetterNCM#525]
### Bug 描述

点击降级那个界面确定后，降级成功后自动打开的网易云没有batterncm插件，重新启动也没有。

### 复现步骤

1. 转到"插件商店
2. 点击'干掉自动更新'
3. 点击确定
4. 看到错误

### 期望行为

修复错误

### 屏幕截图

![微信图片_20241006021009](https://github.com/user-attachments/assets/ca40f724-07b5-42a3-bd21-f1faee9b6c26)

### BetterNCM 版本

1.3.4

### 网易云音乐版本

2.10.13

### 网易云音乐 Patch 版本

1:12f06b8

### 补充

重新安装插件后网易云直接打不开

**Comment by std-microblock** [comment]
降级后需要重新使用安装器安装betterncm
