### ISSUE TITLE
[ Plugin Bug ]bettermcn安装后重新进网易云会崩溃

### ISSUE THREAD

**Issue by WUDIDENIUNIUMA** [std-microblock/BetterNCM#527]
### Bug 描述

安装完bettermcn后，关闭网易云再次打开会显示bettermcn崩溃界面，并且没有bettermcn的图标

### 复现步骤

**例**:
1. 转到"...
2. 点击'....'
3. 向下滚动到'....'
4. 看到错误

### 期望行为

a

### 屏幕截图

![微信图片_20241011104050](https://github.com/user-attachments/assets/ad7a906a-6c03-4123-a9d2-1847668ee26e)

### BetterNCM 版本

1.2.0

### 网易云音乐版本

2.10.13

### 网易云音乐 Patch 版本

1：12f60吧

### 已安装插件

**例**:
- StylesheetLoader
- ActionEnhancement
没有安装插件

### 补充

a

**Comment by std-microblock** [comment]
已修复，MSVC增量编译搞出来的问题

**Comment by std-microblock** [comment]
你的网易云上次没有退出干净，或者第一次是用管理员权限运行的 请检查

**Comment by WUDIDENIUNIUMA** [comment]
> 你的网易云上次没有退出干净，或者第一次是用管理员权限运行的 请检查

卸载重新下载多次了，没有使用管理员权限

**Comment by std-microblock** [comment]
噢 你乱改了数据目录 在安装器内改回去即可

**Comment by WUDIDENIUNIUMA** [comment]
> 噢 你乱改了数据目录 在安装器内改回去即可
试过了，安装器重置选项，还是会这样
