### ISSUE TITLE
安装后网易云无法启动，没反应

### ISSUE THREAD

**Issue by 0623jmq** [std-microblock/BetterNCM#528]
### Bug 描述

安装后无法正常打开网易云音乐

### 复现步骤

从https://microblock.cc/betterncm?ref=biemoyu.com 下载，打开，能正常自寻到网易云地址，安装后，网易云无法打开，打开网易云完全没反应，点击卸载后又自动启动网易云了。

### 期望行为

可以正常使用

### 屏幕截图

![PixPin_2024-10-11_17-03-55](https://github.com/user-attachments/assets/b0119772-672f-436e-ad08-6a37b2f82472)
![PixPin_2024-10-11_17-04-28](https://github.com/user-attachments/assets/3b5c3a89-477d-4c5b-98eb-b8d976b8a229)

### BetterNCM 版本

1.3.4

### 网易云音乐版本

2.10.5

### 网易云音乐 Patch 版本

ec8d6f3

**Comment by mintonight** [comment]
我的之前也是你这个问题，现在成功了。
操作：先卸载插件，正常打开网易云音乐，随便播放几首歌，然后在网易云音乐运行时点击betterncm的安装，网易云会自动重启之后就ok了。
你可以试试

**Comment by std-microblock** [comment]
需要一个可以复现这个问题的给我远程调试一下 现在不清楚是什么问题

**Comment by 0623jmq** [comment]
> 我的之前也是你这个问题，现在成功了。 操作：先卸载插件，正常打开网易云音乐，随便播放几首歌，然后在网易云音乐运行时点击betterncm的安装，网易云会自动重启之后就ok了。 你可以试试

感谢，我试了还是不行。哎。

**Comment by 0623jmq** [comment]
> 需要一个可以复现这个问题的给我远程调试一下 现在不清楚是什么问题

可以的，todesk远程控制方便吗

**Comment by 0623jmq** [comment]
-邀请您进行远程控制
ToDesk设备代码:583 954 131
临时密码:1hr1p4fj
点击链接直接进行远程控制：
https://wechat.todesk.com/invite-page?id=eCZWpUJz6ykG8FjN5xBnj

**Comment by mintonight** [comment]
不好意思，我刚关电脑，现在调不了。另外提醒你一下，你把这个远程的码发出来有泄露的风险。对了，除了我说的那些操作，我还新装了一个 node.js 不知道有没有可能是这个的影响，如果你还是不行，可以加我的 qq 账号1473823447

**Comment by 0623jmq** [comment]
> 不好意思，我刚关电脑，现在调不了。另外提醒你一下，你把这个远程的码发出来有泄露的风险。对了，除了我说的那些操作，我还新装了一个 node.js 不知道有没有可能是这个的影响，如果你还是不行，可以加我的 qq 账号1473823447

没事临时码手动更新掉就好，而且非同一账号需要本机同意。 感谢。

**Comment by 0623jmq** [comment]
> 需要一个可以复现这个问题的给我远程调试一下 现在不清楚是什么问题

好我去录屏复现。

**Comment by 0623jmq** [comment]
https://github.com/user-attachments/assets/4fe0a4b9-e26a-4ded-8a3e-36702fd40c71

**Comment by std-microblock** [comment]
已修复，MSVC增量编译搞出来的问题
