### ISSUE TITLE
安装后无法打开网易云音乐

### ISSUE THREAD

**Issue by Ivoura** [std-microblock/BetterNCM#529]
### Bug 描述

安装BetterNCM后(手动或自动安装)，网易云音乐无法启动。

### 复现步骤

 1 . 从网易云音乐官网下载最新版后安装。
 2 . 从"https://microblock.cc/betterncm" 下载BetterNCM Installer 或 从"https://github.com/std-microblock/BetterNCM/releases/tag/1.3.4" 下载"BetterNCMII.dll"。
(使用 BetterNCM Installer 安装) 3. 获取到适配的BetterNCM版本为1.3.4后，单击安装。
(使用 手动安装) 3. 安装官方文档安装方法，将下好的"BetterNCMII.dll"重命名为"msimg32.dll"后放入网易云音乐安装目录。
 4 . BetterNCM安装后，网易云音乐无法启动。

### 期望行为

在安装BetterNCM后成功运行网易云，且BetterNCM生效并运作良好

### 屏幕截图

![QQ20241012-102758](https://github.com/user-attachments/assets/ed39df0c-dc31-459b-97be-33a1446af71f)
![QQ20241012-103250](https://github.com/user-attachments/assets/193e2661-6834-494a-98bf-abe19325f461)

### BetterNCM 版本

1.3.4

### 网易云音乐版本

3.0.4

### 网易云音乐 Patch 版本

d78a735

### 补充

有一个奇怪的事情...BetterNCM Installer获取到的网易云版本为3.0.18，但是网易云音乐显示的版本为3.0.4

**Comment by Ivoura** [comment]
安装BetterNCM 1.3.3版本可以正常启动网易云音乐

**Comment by std-microblock** [comment]
已修复，MSVC增量编译搞出来的问题

**Comment by INKT-love** [comment]
网易云版本:3.0.15 betterncm最新 还是有同样问题 系统:win10 ltsc
