### ISSUE TITLE
2.10.13版本网易云卸载插件可以运行,但安装插件后则无法启动,官网最新3.x版本则可以

### ISSUE THREAD

**Issue by xiaojiejieouo** [std-microblock/BetterNCM#530]
### Bug 描述

如题,用安装器卸载插件后网易云正常运行,安装后则无法启动

### 复现步骤

下载插件
安装网易云
打开网易云(正常启动)
点击插件,点击安装
网易云无法启动,并且重启电脑后仍旧无法启动
插件内点击卸载
网易云正常启动
点击安装
网易云无法启动,继续循环

### 期望行为

正常启动网易云

### BetterNCM 版本

1.3.4

### 网易云音乐版本

2.10.13 x86

### 网易云音乐 Patch 版本

patch:1:2acb09d

**Comment by xiaojiejieouo** [comment]
补充一下,1.3.4可以用,网易最新版3.x客户端
1.3.3可以用x86的2.10.x客户端

**Comment by Ivoura** [comment]
啊啊啊？我1.3.4安装了启动不了网易云😭

**Comment by xiaojiejieouo** [comment]
> 啊啊啊？我1.3.4安装了启动不了网易云😭

你是官网最新的网易云吗

**Comment by Ivoura** [comment]
是的

**Comment by xiaojiejieouo** [comment]
要不你试试1.33,我都可以用

> 是的

**Comment by Ivoura** [comment]
欸！！！！1.3.3真的可以用欸

**Comment by Ivoura** [comment]
谢谢！！

**Comment by xiaojiejieouo** [comment]
> 谢谢！！

没事

**Comment by std-microblock** [comment]
已修复，MSVC增量编译搞出来的问题
