### ISSUE TITLE
[ Bug ] 安装 BetterNCM 1.3.4 版本后无法启动网易云音乐

### ISSUE THREAD

**Issue by mavnp** [std-microblock/BetterNCM#531]
### Bug 描述

通过 BetterNCM-Installer 安装以及手动安装 BetterNCM 1.3.4 版本均无法正常启动网易云音乐，一旦安装，点击图标无法启动，任务管理器中也没有进程。

### 复现步骤

1 . 从网易云音乐官网下载新版客户端（或旧版客户端，我两个版本都试过了）后安装；
2 . 从"https://github.com/std-microblock/BetterNCM-Installer/releases/download/1.2.0/betterncm_installer.exe" 下载BetterNCM Installer 或 从"https://github.com/std-microblock/BetterNCM/releases/download/1.3.4" 下载"BetterNCMII.dll"（或“BetterNCMII86.dll”）。
3 . 使用 BetterNCM Installer 安装，获取到适配的BetterNCM版本为1.3.4后，单击安装。
![Snipaste_2024-10-18_12-31-13](https://github.com/user-attachments/assets/90993451-9eca-4db3-b78d-e8101a1574d9)
(或手动安装，按照官方文档手动安装方法，将下好的"BetterNCMII.dll"重命名为"msimg32.dll"后放入网易云音乐安装目录。) 
4 . BetterNCM安装后，网易云音乐无法启动，且任务管理器中没有对应进程。

### 期望行为

在安装BetterNCM后成功运行网易云，且BetterNCM生效并运作良好

### 屏幕截图

![Snipaste_2024-10-18_12-31-13](https://github.com/user-attachments/assets/9ad07cb2-1e23-4788-9f3e-3b5dfe5eb497)

https://github.com/user-attachments/assets/e38cb3c1-a07f-455d-bb80-c1dd73730f80

### BetterNCM 版本

1.3.4

### 网易云音乐版本

2.10.13(x86)

### 网易云音乐 Patch 版本

1:2acb09d

### 补充

手动安装 BetterNCM 1.3.3 版本可以正常启用网易云音乐

**Comment by std-microblock** [comment]
可以在群内找我远程调试一下

**Comment by Bycorer** [comment]
> 可以在群内找我远程调试一下

是的我也遇到了，操作系统win 11 .24h2, 测试网易云版本：3.0.18，3.0.19，3.0.1，3.0.5，2.10.13，2.10.10，2.10.18，手动或自动都无法使用，希望修复

**Comment by BuGanItk** [comment]
+1

**Comment by G1t-hub** [comment]
win10 全新安装网易云3.0.19(Build 203184 Patch 096be2c)后使用安装器安装BetterNCM 1.3.4 同闪退，启动后进程立即崩溃退出并生成dmp文件。卸载后手动安装1.3.3恢复正常

**Comment by Bycorer** [comment]
已经正常使用

**Comment by Fe4FeCN63** [comment]
遇到相同问题，安装BetterNCM 1.3.4后尝试启动时提示“C:\Program Files\NetEase\CloudMusic\MSIMG32.dll没有被指定在Windows上运行，或者它包含错误”
![屏幕截图 2024-11-02 084224](https://github.com/user-attachments/assets/8b14fbe4-9289-40c0-bb0f-506746d4c148)
![屏幕截图 2024-11-02 084158](https://github.com/user-attachments/assets/3e527378-13f3-415b-a6d9-e9fb1453a98b)

**Comment by G1t-hub** [comment]
> 启动时提示“C:\Program Files\NetEase\CloudMusic\MSIMG32.dll没有被指定在Windows上运行，或者它包含错误”

同遇到过，查看MSIMG32.dll文件内容发现是xml格式的错误日志，应该是Installer的下载过程出了问题。建议installer能识别出下载错误的情况并提示用户。

**Comment by std-microblock** [comment]
我服务器端配置问题，已修复

**Comment by Lukoning** [comment]
> > 我服务器端配置问题，已修复
> 
> 才点的更新 ![image](https://private-user-images.githubusercontent.com/92252063/382481281-116844a3-53d4-437b-9ae3-fc6d4623a77a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NjAzOTgsIm5iZiI6MTczMDU2MDA5OCwicGF0aCI6Ii85MjI1MjA2My8zODI0ODEyODEtMTE2ODQ0YTMtNTNkNC00MzdiLTlhZTMtZmM2ZDQ2MjNhNzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDE1MDgxOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFiMWUwN2Y3ZjRiYjczZjg1NWFhZjY3NmI4OGExMWJlNWY0MzQ2N2Q5NDY2MThkYTZjYWE2MGQ5YWY4YzAxNGYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.rTCcqhtb5lMarQXD4IzNRQPUaa0zWApujosLfF7r3TI)

再次复现成功
安装1.3.3 -> 在网易云内点击更新 -> 弹UAC，点是 -> 网易云关闭后报错
![image](https://github.com/user-attachments/assets/d9b46aae-b13d-4be5-b592-171a1f642b87)

**Comment by std-microblock** [comment]
> > 我服务器端配置问题，已修复
> 
> 才点的更新 ![image](https://private-user-images.githubusercontent.com/92252063/382481281-116844a3-53d4-437b-9ae3-fc6d4623a77a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzA1NjMyMTksIm5iZiI6MTczMDU2MjkxOSwicGF0aCI6Ii85MjI1MjA2My8zODI0ODEyODEtMTE2ODQ0YTMtNTNkNC00MzdiLTlhZTMtZmM2ZDQ2MjNhNzdhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTAyVDE1NTUxOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTExYWI2ODhiMmE2NTM1OTg3MGNhZDI2NzUxZDRmODUxOGZmMjczOTk1ZWVlZTVhODAzMGUzOWJjYWU5ZDM1MzAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.JPlU74do5B4SKWKaQA9xkeNb7cnRogUQykC9uK-hqsY)

有可能还有缓存 过一个小时再看看

**Comment by bg3h** [comment]
24H2系统与楼主描述一致

**Comment by bg3h** [comment]
24H2系统与楼主描述一致 卸载后网易云音乐就立刻运行了

**Comment by bg3h** [comment]
手动安装x86的1.3.3 版本2.10.13.202675可以使用，在网易云内更新后仍旧复现

**Comment by SettingDust** [comment]
复现，无法启动，无任何提示，事件查看器中有报错
![图片](https://github.com/user-attachments/assets/c72b054a-cd4d-4c8c-a6fb-8c07f1895851)

**Comment by Lukoning** [comment]
可能有点晚了，11月13号中午在学校电脑复现，且不论使用安装器还是手动安装都无法启动；手动安装1.3.3版本无此问题。

https://github.com/user-attachments/assets/a655ba81-af7e-419c-9ff6-62917ef2bf26

**Comment by bg3h** [comment]
2024/11/23在网易云音乐内更新到1.3.4版本后正常
