### ISSUE TITLE
[ Bug ] 崩溃原因：create directories：系统找不到指定路径。

### ISSUE THREAD

**Issue by 744211880** [std-microblock/BetterNCM#546]
### Bug 描述

BetterNCM 崩溃

崩溃原因：create directories：系统找不到指定路径。
“C：betterncm/plugins”

我怀疑是因为直接特指某盘符导致的

### 复现步骤

系统装在其他盘符的磁盘，导致整机并没有使用字母C作为盘符的磁盘存在。
然后使用把提供的dll文件放在网易云下载地址，就会提示此错误。

### 期望行为

希望能不要指定盘符，而是可以自动识别空闲磁盘或者遍历字母盘符直到找到存在的磁盘。

### 屏幕截图

![1735138006176](https://github.com/user-attachments/assets/dc52b8c3-b4ff-4f96-acdf-e9ee1c4dfb3d)

### BetterNCM 版本

1.3.4

### 网易云音乐版本

3.1.2

### 网易云音乐 Patch 版本

91d0ddb

### 补充

目前大多都是猜测，希望能回复下来告诉我这是bug还是我的操作失误。

**Comment by 744211880** [comment]
我新增了C盘符的磁盘后，此崩溃就不再发生了。

**Comment by std-microblock** [comment]
手动修改数据目录即可
