### ISSUE TITLE
类苹果歌词插件不显示歌词 只有左边的控件比如专辑封面

### ISSUE THREAD

**Issue by Aixscape** [std-microblock/BetterNCM#547]
### Bug 描述

类苹果歌词插件不显示歌词 只有左边的控件比如专辑封面

### 复现步骤

点进歌词界面即可复现

### 期望行为

请修复

### 屏幕截图

![屏幕截图 2024-12-26 030545](https://github.com/user-attachments/assets/c31f99c1-f8d8-4f6c-9f18-c9562c681d12)

### BetterNCM 版本

3.1.0

### 网易云音乐版本

3.1.2

### 网易云音乐 Patch 版本

91d0ddb

### 已安装插件

类苹果歌词
TinyNCM

**Comment by FinaFina233** [comment]
![image](https://github.com/user-attachments/assets/9043bbeb-cb37-4063-92a1-5e87122163f6)
插件相关发这里没用，不是他做的，而且原插件也停更了，没歌词多半你自己调歌词源了

**Comment by std-microblock** [comment]
在歌词源里把第二个调成第一个
